export enum AuthSteps {
    LOGIN_STEP = 'LOGIN_STEP',
    RESET_PASSWORD_STEP = 'RESET_PASSWORD_STEP',
    RECOVER_PASSWORD_STEP = 'RECOVER_PASSWORD_STEP',
    REGISTRATION_STEP = 'REGISTRATION_STEP',
}