export const SUGGESTIONS_SUCCESS = 'SUGGESTIONS_SUCCESS';
export const SUGGESTIONS_INIT = 'SUGGESTIONS_INIT';
export const SUGGESTIONS_ERROR = 'SUGGESTIONS_ERROR';

export const TRENDING_SUCCESS = 'TRENDING_SUCCESS';
export const TRENDING_INIT = 'TRENDING_INIT';
export const TRENDING_ERROR = 'TRENDING_ERROR';

export const THEMES_SUCCESS = 'THEMES_SUCCESS';
export const THEMES_INIT = 'THEMES_INIT';
export const THEMES_ERROR = 'THEMES_ERROR';
